# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  check_dawn:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - job_name: 'staff store, custom app login'
            store: shimmering-islands.myshopify.com
            access_token: SHOP_ACCESS_TOKEN
            password: ''

          - job_name: 'dev store, custom app login'
            store: cpclermont-dev-store.myshopify.com
            access_token: DEV_ACCESS_TOKEN
            password: DEV_PASSWORD

    name: ${{ matrix.job_name }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "shopify/dawn"
          path: "./dawn"

      - name: Lighthouse CI action
        uses: ./
        id: lighthouse-ci-action
        with:
          access_token: ${{ secrets[matrix.access_token] }}
          store: ${{ matrix.store }}
          password: ${{ secrets[matrix.password] }}
          theme_root: "./dawn"
          lhci_min_score_performance: 0.1
          lhci_min_score_accessibility: 0.1
